name: flutter_album
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.7+4
  image_gallery_saver: ^1.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_common:
    git:
      url: 'https://github.com/asd451398533/flutter_common.git'
      ref: '06d55727aa7358b792c13bbc07bbdb1749eb12ba'
  gengmei_flutter_plugin:
    git:
      url: '/Users/apple/lsy/gengmei_flutter_plugin'

flutter:

