name: flutter_album
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.7+4
  image_gallery_saver: ^1.2.2

#  flutter_common:
#    git:
#      url: 'https://github.com/asd451398533/flutter_common.git'
#      ref: '0abdb58403883249ccd556b4f0cdeaaf6e9a3d76'
#  gengmei_flutter_plugin:
#    git:
#      url: '/Users/apple/lsy/gengmei_flutter_plugin'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

